### ISSUE TITLE
add client side example

### ISSUE THREAD

**Issue by geometry88** [chaeyk/eac-leak#1]
add client side example

**Comment by chaeyk** [comment]
Memory leak exists on server side API (EOS_AntiCheatServer_RegisterClient or EOS_AntiCheatServer_UnregisterClient)
You can run this test with server project. (server.cpp main())

And, problem was fixed. You don't need to run this program, anymore.
https://eoshelp.epicgames.com/s/question/0D74z00000ALKstCAH/detail?language=en_US&fromEmail=1&s1oid=00D1a000000L44R&s1nid=0DB2L000000PBY1&s1uid=0054z000009li7G&s1ext=0&emkind=chatterCommentNotification&emtm=1641377646100
https://dev.epicgames.com/docs/epic-online-services/whats-new#1142---2022-feb-01
